2025-07-01 06:51:33,162 INFO ====== WebDriver manager ======
2025-07-01 06:51:33,332 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 06:51:33,662 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 06:51:33,987 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 07:15:45,847 INFO ====== WebDriver manager ======
2025-07-01 07:15:46,025 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 07:15:47,440 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 07:15:47,842 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 08:43:02,610 INFO ====== WebDriver manager ======
2025-07-01 08:43:02,782 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 08:43:04,224 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 08:43:04,669 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 08:46:50,765 ERROR Fatal error in main
Traceback (most recent call last):
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbookpro/projects/espscraper-project/espscraper/__main__.py", line 88, in main
    scraper.scrape_all_details(force_relogin=args.force_relogin)
  File "/Users/macbookpro/projects/espscraper-project/espscraper/scrape_product_details.py", line 558, in scrape_all_details
    self.login(force_relogin=force_relogin)
  File "/Users/macbookpro/projects/espscraper-project/espscraper/scrape_product_details.py", line 84, in login
    self.driver.refresh()
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 716, in refresh
    self.execute(Command.REFRESH)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 445, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=64713): Read timed out. (read timeout=120)
2025-07-01 09:07:32,867 INFO ====== WebDriver manager ======
2025-07-01 09:07:33,172 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:07:34,409 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:07:34,885 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 09:08:25,366 INFO ====== WebDriver manager ======
2025-07-01 09:08:25,537 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:08:25,858 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:08:26,219 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 09:08:27,120 INFO ====== WebDriver manager ======
2025-07-01 09:08:27,260 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:08:27,718 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:08:28,093 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 09:11:18,990 ERROR Fatal error in main
Traceback (most recent call last):
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbookpro/projects/espscraper-project/espscraper/__main__.py", line 88, in main
    scraper.scrape_all_details(force_relogin=args.force_relogin)
  File "/Users/macbookpro/projects/espscraper-project/espscraper/scrape_product_details.py", line 558, in scrape_all_details
    self.login(force_relogin=force_relogin)
  File "/Users/macbookpro/projects/espscraper-project/espscraper/scrape_product_details.py", line 77, in login
    self.driver.get(self.PRODUCTS_URL)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 472, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 445, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=56695): Read timed out. (read timeout=120)
2025-07-01 09:49:44,880 INFO ====== WebDriver manager ======
2025-07-01 09:49:45,075 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:49:46,074 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:49:46,862 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 09:53:47,696 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=53361): Read timed out. (read timeout=120)")': /session/64f880f40ed1d9d6faae84b49bc11306
2025-07-01 09:53:48,116 INFO ====== WebDriver manager ======
2025-07-01 09:53:48,261 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:53:49,436 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:53:49,875 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 09:53:50,940 INFO ====== WebDriver manager ======
2025-07-01 09:53:51,090 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:53:51,640 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 09:53:52,243 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 09:54:23,019 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1050a9970>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b29a6dfc92c0e32489b41e5e2507b9bf
2025-07-01 09:54:23,021 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1050a9a60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b29a6dfc92c0e32489b41e5e2507b9bf
2025-07-01 09:54:23,024 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1050a9370>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b29a6dfc92c0e32489b41e5e2507b9bf
2025-07-01 10:44:35,944 INFO ====== WebDriver manager ======
2025-07-01 10:44:36,134 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 10:44:37,305 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 10:44:38,567 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 10:48:35,428 INFO ====== WebDriver manager ======
2025-07-01 10:48:35,569 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 10:48:36,056 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 10:48:36,960 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 10:48:38,022 INFO ====== WebDriver manager ======
2025-07-01 10:48:38,175 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 10:48:40,107 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 10:48:42,082 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 10:55:36,116 ERROR Fatal error in main
Traceback (most recent call last):
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbookpro/projects/espscraper-project/espscraper/__main__.py", line 88, in main
    scraper.scrape_all_details(force_relogin=args.force_relogin)
  File "/Users/macbookpro/projects/espscraper-project/espscraper/scrape_product_details.py", line 558, in scrape_all_details
    self.login(force_relogin=force_relogin)
  File "/Users/macbookpro/projects/espscraper-project/espscraper/scrape_product_details.py", line 84, in login
    self.driver.refresh()
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 716, in refresh
    self.execute(Command.REFRESH)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 445, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/macbookpro/projects/espscraper-project/espenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=55373): Read timed out. (read timeout=120)
2025-07-01 14:17:46,947 INFO ====== WebDriver manager ======
2025-07-01 14:17:47,142 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 14:17:47,747 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 14:17:48,038 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 14:18:19,135 INFO ====== WebDriver manager ======
2025-07-01 14:18:19,311 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 14:18:20,183 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 14:18:20,371 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
2025-07-01 14:18:21,263 INFO ====== WebDriver manager ======
2025-07-01 14:18:21,422 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 14:18:21,708 INFO Get LATEST chromedriver version for google-chrome
2025-07-01 14:18:22,066 INFO Driver [/Users/macbookpro/.wdm/drivers/chromedriver/mac64/137.0.7151.119/chromedriver-mac-arm64/chromedriver] found in cache
